### PR TITLE
Full update of all pages based on @lawinslow and @eread-USGS changes

### PR DESCRIPTION
**Pull request by lawinslow**
@eread-usgs this stuff looks great!

### CODE REVIEW

**Comment by jread-usgs** [comment]
Did you two still need plotting? I have some time this am to contribute if needed.

**Comment by lawinslow** [comment]
@jread-USGS yes please! Much appreciated.

**Comment by jread-usgs** [comment]
OK, assuming this: http://usgs-r.github.io/introR/2015/01/14/04-Explore/ is the target

**Comment by lawinslow** [comment]
Here is your target. That other one is base already. 

https://github.com/USGS-R/introR/blob/gh-pages/rmd_posts/2015-01-15-07-Visualize.Rmd

**Comment by jread-usgs** [comment]
That is going to take a bit more time than I have this am. What is the timeline?

**Comment by jread-usgs** [comment]
@lawinslow or @eread-usgs what is the timeline?

**Comment by eread-usgs** [comment]
@jread-usgs @lawinslow needs it done by Sunday

**Comment by jread-usgs** [comment]
Ok, I'm already on the hook! (didn't realize there was already an issue: https://github.com/USGS-R/introR/issues/15) Will have it, but please keep me in the loop if the earlier section example data changes and I should know about it.

**Pull request merged**
